;;; Unilex scheme definition.

;; RPX version.

(defvar unilexdir (path-append lexdir "unilex"))

(require 'pos)
(require 'unilex_phones)

(define (unilex-rpx_lts_function word feats)
  "(unilex_lts_function word feats)
Function called for UNILEX when word is not found in lexicon.  Uses
LTS rules trained from the original lexicon, and lexical stress
prediction rules."
  (require 'lts)
  (if (not (boundp 'unilex-rpx_lts_rules))
      (load (path-append unilexdir "unilex-rpx_lts_rules.scm")))
  (let ((dcword (downcase word))
        (syls) (phones))
    (if (string-matches dcword "[a-z\-]*")
        (begin
          (set! phones (lts_predict dcword unilex-rpx_lts_rules))
          (set! syls (lex.syllabify.phstress phones))
          )
        (set! syls nil))
    (list word nil syls)))

;; This list is built by manually taking pronounciations for abbreviations
;; from their full entries in the compiled lexicon.
(define (unilex-rpx_addenda)
  "(unilex-rpx_addenda)
Add entries to the current lexicon.  These are basically
words that are not in the keyword lexicon."
  (lex.add.entry
   '("Jan" nnp ((( jh a ) 1)((n y uw @) 0)((r iy) 0))))
  (lex.add.entry
   '("Feb" nnp ((( f e ) 1)((b r uw @) 0)((r iy) 0))))
  (lex.add.entry
   '("Mar" nnp  ((( m aa ch ) 1))))
  (lex.add.entry
   '("Apr" nnp ((( ei ) 1)((p r i lw) 0))))
  (lex.add.entry
   '("Jun" nnp ((( jh uu n ) 1))))
  (lex.add.entry
   '("Jul" nnp  (((jh u ) 0)(( l ai ) 1))))
  (lex.add.entry
   '("Aug" nnp ((( oo ) 1)((g @ s t ) 0))))
  (lex.add.entry
   '("Sep" nnp (((s e p ) 0)(( t e m ) 1)((b @ ) 0))))
  (lex.add.entry
   '("Sept" nnp (((s e p ) 0)(( t e m ) 1)((b @ ) 0))))
  (lex.add.entry
   '("Oct" nnp (((oo k ) 0)(( t ou ) 1)((b @ ) 0))))
  (lex.add.entry
   '("Nov" nnp (((n ou ) 0)(( v e m ) 1)((b @ ) 0))))
  (lex.add.entry
   '("Dec" nnp (((d i ) 0)(( s e m ) 1)((b @ ) 0))))
  (lex.add.entry
   '("'s" pos (((@ z) 0))))   ; ?
  (lex.add.entry 
   '("*" nn ((( a ) 1)((s t @ ) 0)((r i s k ) 0))))
  (lex.add.entry 
   '("%" nn (((p @ ) 0)(( s e n t ) 1))))
  (lex.add.entry 
   '("&" nn ((( a m ) 1)((p @ ) 0)(( s a n d ) 2))))
  (lex.add.entry 
   '("$" nn ((( d o ) 1)((l @ ) 0))))
  (lex.add.entry 
   '("#" nn ((( h a sh ) 1))))
  (lex.add.entry 
   '("@" n (((a t) 1))))
  (lex.add.entry 
   '("+" cc ((( p l uh s ) 1))))
  (lex.add.entry 
   '("^" nn ((( k a ) 1)((r @ t ) 0))))
  (lex.add.entry 
   '("~" nn ((( t i lw ) 1)((d @ ) 0))))
  (lex.add.entry 
   '("=" nns ((( ii ) 1)((k w @ lw z ) 0))))
  (lex.add.entry 
   '("/" nn ((( s l a sh ) 1))))
  (lex.add.entry 
   '("\\" nn ((( b a k ) 1)(( s l a sh ) 3))))
  (lex.add.entry 
   '("_" nn ((( uh n ) 1)((d @) 0)(( s k oo ) 2))))
  (lex.add.entry 
   '("|" nn ((( v @@r ) 2)((t i ) 0)((k l! ) 0)(( b aa ) 1))))
  (lex.add.entry 
   '(">" nn ((( g r ei t ) 1)((@ ) 0)(( dh @ n ) 0))))
  (lex.add.entry 
   '("<" nn ((( l e s ) 1)(( dh @ n ) 0))))
  (lex.add.entry 
   '("[" nn ((( l e f t ) 3)(( b r a ) 1)((k i t ) 0))))
  (lex.add.entry 
   '("]" nn ((( r ai r ) 3)(( b r a ) 1)((k i t ) 0))))
  (lex.add.entry 
   '(" " nn ((( s p ei s ) 1))))
  (lex.add.entry 
   '("\t" nn  ((( t a b ) 1))))
  (lex.add.entry 
   '("\n" nn  ((( n y uu ) 1)(( l ai n ) 3))))
  (lex.add.entry '("." punc nil))
  (lex.add.entry '("'" punc nil))
  (lex.add.entry '(":" punc nil))
  (lex.add.entry '(";" punc nil))
  (lex.add.entry '("," punc nil))
  (lex.add.entry '("-" punc nil))
  (lex.add.entry '("\"" punc nil))
  (lex.add.entry '("`" punc nil))
  (lex.add.entry '("?" punc nil))
  (lex.add.entry '("!" punc nil))

; load airport names.
(load (path-append unilexdir "bathrooms-rpx.scm"))

; other addenda

  (lex.add.entry
   '("paroxysm" nn (((p a) 1) ((r @ k) 0) ((s i) 0) ((z m!) 0))))
  (lex.add.entry
   '("plasmodium" nnp (((p l a z) 0) ((m ou d) 1) ((iy) 0) ((@ m) 0))))
  (lex.add.entry
   '("plasmodia" nnp (((p l a z) 0) ((m ou d) 1) ((iy) 0) ((@) 0))))
  (lex.add.entry
   '("tertian" jj (((t @@r) 1)((sh n!) 0))) )
  (lex.add.entry
   '("quartan" jj (((k w oo t) 1) ((@ n) 0))) )
  (lex.add.entry
   '("HIV" nnp (((ei ch) 1) ((ai) 1) ((v ii) 1))))

; acrtic omissions

  (lex.add.entry '("etc" nn (((e t) 0) ((s e) 1) ((t @) 0) ((r @) 0))))
  (lex.add.entry '("Whittemore" nnp (((w i t) 1) ((m oo) 0))))
  (lex.add.entry '("borealis" nnp (((b oo) 2) ((r ii) 0) ((aa) 1) ((l i s) 0) )))
  (lex.add.entry '("nightglow" nn (((n ai t) 1) ((g l ou) 2))) )
  (lex.add.entry '("worshiped" vbd (((w @@r) 1) ((sh i p t) 0))) )
  (lex.add.entry '("gallina" nnp (((g @) 0) ((l ii) 1) ((n @) 0))))
  (lex.add.entry '("patino" jj (((p a) 0) ((t ii) 1) ((n ou) 0))))
  (lex.add.entry '("shunk" nn (((sh uh ng k) 1))))
  (lex.add.entry '("oolong" nnp (((uu) 1) ((l o ng) 0))) )
  (lex.add.entry '("Hanrahan" nil (((h a n) 1) ((r @) 0) ((h a n) 0))))
  (lex.add.entry '("mab" nnp (((m a b) 1))))
  (lex.add.entry '("unwin" nnp (((uh n) 1) ((w i n) 0))))
  (lex.add.entry '("Perrault" nnp (((p eir) 0) ((r ou lw t) 1))))
  (lex.add.entry '("Wada" nnp (((w ei d) 1) ((@) 0))) )
  (lex.add.entry '("Nakata" nil (((n a) 0) ((k aa) 0) ((t @) 0))))
  (lex.add.entry '("tambo" nn (((t a m) 1) ((b ou) 0))))
  (lex.add.entry '("kerfoot" nnp (((k @@r) 1) ((f u t) 0))))
  (lex.add.entry '("spink" nnp (((s p i ng k) 1))))
  (lex.add.entry '("corry" nnp (((k o) 1) ((r iy) 0))))
  (lex.add.entry '("ee" nil (((ii) 0))))
  (lex.add.entry '("molokai" nnp (((m o) 1) ((l ou) 0) ((k ii) 0))))
  (lex.add.entry '("niiau" nnp (((n ii) 0) ((h ow) 1))))
  (lex.add.entry '("claudine" nnp (((k l oo) 0)((d ii n) 1))))
  (lex.add.entry '("Pasquini" nnp (((p a) 0) ((s k w ii) 1) ((n ii) 0))))
  (lex.add.entry '("Waikiki" nnp (((w ai) 1) ((k ii ) 2) ((k ii) 2))))
  (lex.add.entry '("Oahu" nnp (((@) 0) ((w aa) 1) ((h uu) 0))))
  (lex.add.entry '("womble" nn (((w o m) 1) ((b u lw) 0))))
  (lex.add.entry '("dennin" nnp (((d e) 1) ((n i n) 0))) )
  (lex.add.entry '("linderman" nnp (((l i n) 1) ((d @) 0) ((m @ n) 0))))
  (lex.add.entry '("daughtry" nn (((d oo) 1) ((t r ii) 0))))
  (lex.add.entry '("fitzhugh" nnp (((f i t s) 1) ((h y uu) 1))))
  (lex.add.entry '("roscoe" nnp (((r o s) 1) ((k ou) 0))))
  (lex.add.entry '("billinger" nnp (((b i) 1) ((lw i n) 0) ((jh @) 0))) )
  (lex.add.entry '("elam" nnp (((ii) 1) ((l a m) 0))))
  (lex.add.entry '("harnish" nnp (((h aa) 1) ((n i sh) 0))))
  (lex.add.entry '("howison" nnp (((h ow) 1) ((i) 0) ((s n!) 0))))
  (lex.add.entry '("tse" nnp (((t s ii) 1))))
  (lex.add.entry '("sandel" nnp (((s a n) 1) ((d l!) 0))))
  (lex.add.entry '("chauncey" nnp (((ch oo n) 1) ((s ii) 0))))
  (lex.add.entry '("depew" nnp (((d ii) 0) ((p y uu) 1))))
  (lex.add.entry '("brinker" nnp (((b r i ng k) 1) ((@) 0))))
  (lex.add.entry '("roadmate" nn (((r ou d) 1) ((m ei t) 3))))
  (lex.add.entry '("zilla" nnp (((z i) 1) ((l @) 0))))
  (lex.add.entry '("oona" nnp (((uu) 1) ((n @) 0))))
  (lex.add.entry '("Doane" nnp (((d ou n) 1))))

  (lex.add.entry '("hippolyta" nil ( ((h i ) 0) (( p o ) 1) (( l i ) 0) (( t @ ) 0)  )))
  (lex.add.entry '("egeus" nil ( ((i ) 0) (( jh ii ) 1) (( @ s ) 0)  )))
  (lex.add.entry '("hermia" nil ( ((h @@r ) 1) (( m ii ) 0) (( @ ) 0)  )))
  (lex.add.entry '("demetrius" nil ( ((d i ) 0) (( m ii t ) 1) (( r ii ) 0) (( @ s ) 0)  )))
  (lex.add.entry '("lysander" nil ( ((l ai ) 0) (( s a n ) 1) (( d @ r ) 0)  )))
  (lex.add.entry '("hermia's" nil ( ((h @@r ) 1) (( m ii ) 0) (( @ z ) 0)  )))
  (lex.add.entry '("titania" nil ( ((t ii ) 0) (( t aa ) 1) (( n ii ) 0) (( @ ) 0)  )))
  (lex.add.entry '("pyramus" nil ( ((p i ) 1) (( r @ ) 0) (( m @ s ) 0)  )))
  (lex.add.entry '("thisbe" nil ( ((th i s ) 0) (( b ii ) 0)  )))
  (lex.add.entry '("whatever's" nil ( ((w o ) 0) (( t e ) 1) (( v @ z ) 0)  )))
  (lex.add.entry '("titania's" nil ( ((t ii ) 0) (( t aa ) 1) (( n ii ) 0) (( @ z ) 0)  )))
  (lex.add.entry '("dewberries" nil ( ((d y uu ) 1) (( b @ ) 0) (( r ii z ) 0)  )))
  (lex.add.entry '("lysander's" nil ( ((l ai ) 0) (( s a n ) 1) (( d @ z ) 0)  )))
  (lex.add.entry '("demetrius's" nil ( ((d i ) 0) (( m ii t ) 1) (( r ii ) 0) (( @ s ) 0)  )))
  (lex.add.entry '("mairi" nil ( ((m aa ) 1) (( r ii ) 0)  )))
  (lex.add.entry '("usborne" nil ( ((uh s ) 1) (( b oo n ) 1)  )))
  (lex.add.entry '("androcles" nil ( ((a n d ) 1) (( r ou k ) 0) (( l ii z ) 0)  )))
  (lex.add.entry '("clinkus" nil ( ((k l i ng ) 1) (( k @ s ) 0)  )))
  (lex.add.entry '("courtauld" nil ( ((k oo ) 1) (( t oo lw d ) 0)  )))
  (lex.add.entry '("asiatic" nil ( ((ei ) 1) (( z ii ) 0) (( a ) 1) (( t i k ) 0)  )))
  (lex.add.entry '("richmore" nil ( ((r i ch ) 1) (( m oo r ) 0)  )))
  (lex.add.entry '("licken" nil ( ((l i k n! ) 1)  )))
  (lex.add.entry '("henny" nil ( ((h e ) 1) (( n ii ) 0)  )))
  (lex.add.entry '("locky" nil ( ((l o ) 1) (( k ii ) 0)  )))
  (lex.add.entry '("ducky" nil ( ((d uh ) 1) (( k ii ) 0)  )))
  (lex.add.entry '("loosey" nil ( ((l uu ) 1) (( s ii ) 0)  )))
  (lex.add.entry '("lurkey" nil ( ((l @@r ) 1) (( k ii ) 0)  )))
  (lex.add.entry '("loxy" nil ( ((l o k ) 1) (( s ii ) 0)  )))
  (lex.add.entry '("brachiosaurus" nil ( ((b r a ) 1) (( k ii ) 0) (( @ ) 0) (( s oo ) 0) (( r @ s ) 0)  )))
  (lex.add.entry '("allosaurus" nil ( ((a ) 1) (( l @ ) 0) (( s oo ) 0) (( r @ s ) 0)  )))
  (lex.add.entry '("gallimimus" nil ( ((g a ) 0) (( l i ) 0) (( m ai ) 1) (( m @ s ) 0)  )))
  (lex.add.entry '("spinosaurus" nil ( ((s p ai ) 1) (( n @ ) 0) (( s oo ) 0) (( r @ s ) 0)  )))
  (lex.add.entry '("corythosaurus" nil ( ((k oo ) 0) (( r i ) 1) (( th @ ) 0) (( s oo ) 0) (( r @ s ) 0)  )))
  (lex.add.entry '("tsintaosaurus" nil ( ((t s i n ) 1) (( d a ) 0) (( @ ) 0) (( s oo ) 0) (( r @ s ) 0)  )))
  (lex.add.entry '("saurolophus" nil ( ((s oo ) 0) (( r @ ) 0) (( l ou ) 1) (( f @ s ) 0)  )))
  (lex.add.entry '("parasaurolophus" nil ( ((p a ) 1) (( r @ ) 0) (( s oo ) 1) (( r @ ) 0) (( l ou ) 1) (( f @ s ) 0)  )))
  (lex.add.entry '("ornitholestes" nil ( ((oo ) 2) (( n i ) 0) (( th @ ) 0) (( l e s ) 1) (( t ii s ) 0)  )))
  (lex.add.entry '("scutellosaurus" nil ( ((s k @ ) 0) (( t e ) 1) (( l @ ) 0) (( s oo ) 2) (( r @ s ) 0)  )))
  (lex.add.entry '("micropachycephalosaurus" nil ( ((m ai k ) 1) (( r @ ) 0) (( p a ) 1) (( k ii ) 0) (( s e ) 1) (( f @ ) 0) (( l @ ) 0) (( s oo ) 1) (( r @ s ) 0)  )))
  (lex.add.entry '("eoraptors" nil ( ((eir ) 1) (( r a p ) 2) (( t @ z ) 0)  )))
  (lex.add.entry '("mussaurus" nil ( ((m u ) 0) (( s oo ) 1) (( r @ s ) 0)  )))
  (lex.add.entry '("plesiosaurs" nil ( ((p l ii ) 1) (( z ii ) 0) (( @ ) 0) (( s oo z ) 1)  )))
  (lex.add.entry '("plesiosaur" nil ( ((p l ii ) 1) (( z ii ) 0) (( @ ) 0) (( s oo r ) 1)  )))
  (lex.add.entry '("velociraptors" nil ( ((v @ ) 0) (( l o ) 1) (( s @ ) 0) (( r a p ) 1) (( t @ z ) 0)  )))
  (lex.add.entry '("tarbosaurus" nil ( ((t aa ) 1) (( b @ ) 0) (( s oo ) 1) (( r @ s ) 0)  )))
  (lex.add.entry '("dromiceiomimus" nil ( ((d r ou ) 0) (( m i ) 1) (( s i@ ) 0) (( @ ) 0) (( m ai ) 1) (( m @ s ) 0)  )))
  (lex.add.entry '("khaan" nil ( ((k aa n ) 1)  )))
  (lex.add.entry '("iguanodon" nil ( ((i g ) 0) (( w a ) 1) (( n @ ) 0) (( d o n ) 0)  )))
  (lex.add.entry '("leaellynasaura" nil ( ((l ii ) 1) (( @ ) 0) (( l i ) 1) (( n @ ) 0) (( s oo ) 1) (( r @ ) 0)  )))
  (lex.add.entry '("orodromeus" nil ( ((o ) 2) (( r @ d ) 0) (( r ou ) 1) (( m ii ) 0) (( @ s ) 0)  )))
  (lex.add.entry '("maiasaura" nil ( ((m ai ) 1) (( @ ) 0) (( s oo ) 1) (( r @ ) 0)  )))
  (lex.add.entry '("edmontosaurus" nil ( ((e d ) 0) (( m o n ) 1) (( t @ ) 0) (( s oo ) 1) (( r @ s ) 0)  )))
  (lex.add.entry '("timeline" nil ( ((t ai m ) 1) (( l ai n ) 2)  )))
  (lex.add.entry '("coloradisaurus" nil ( ((k o ) 0) (( l @ ) 0) (( r aa ) 1) (( d i ) 0) (( s oo ) 1) (( r @ s ) 0)  )))
  (lex.add.entry '("riojasaurus" nil ( ((r ii ) 0) (( o ) 1) (( k @ ) 0) (( s oo ) 1) (( r @ s ) 0)  )))
  (lex.add.entry '("velociraptor" nil ( ((v @ ) 0) (( l o ) 1) (( s @ ) 0) (( r a p ) 1) (( t @ r ) 0)  )))
  (lex.add.entry '("oops''." nil ( ((uu p s ) 1)  )))
  (lex.add.entry '("snippety" nil ( ((s n i ) 1) (( p @ ) 0) (( t ii ) 0)  )))
  (lex.add.entry '("dunsinane" nil ( ((d uh n ) 1) (( s i ) 0) (( n ei n ) 1)  )))
  (lex.add.entry '("cawdor" nil ( ((k oo ) 1) (( d oo r ) 2)  )))
  (lex.add.entry '("fleance" nil ( ((f l ii ) 1) (( @ n s ) 0)  )))
  (lex.add.entry '("birnam" nil ( ((b @@r n m! ) 1)  )))
  (lex.add.entry '("macduff's" nil ( ((m @ k ) 0) (( d uh f s ) 1)  )))
  (lex.add.entry '("milbourne" nil ( ((m i lw ) 1) (( b oo n ) 0)  )))
  (lex.add.entry '("gaston" nil ( ((g a s ) 1) (( t o n ) 2)  )))
  (lex.add.entry '("leroux" nil ( ((l @ ) 0) (( r uu ) 1)  )))
  (lex.add.entry '("knighton" nil ( ((n ai t n! ) 1)  )))
  (lex.add.entry '("carlotta" nil ( ((k aa ) 0) (( l o ) 1) (( t @ ) 0)  )))
  (lex.add.entry '("pico" nil ( ((p ii ) 1) (( k ou ) 0)  )))
  (lex.add.entry '("lamplit" nil ( ((l a m p ) 1) (( l i t ) 0)  )))
  (lex.add.entry '("fourty" nil ( ((f oo ) 1) (( t ii ) 0)  )))
  (lex.add.entry '("patchett" nil ( ((p a ) 1) (( ch i t ) 0)  )))
  (lex.add.entry '("carabas" nil ( ((k a ) 1) (( r @ ) 0) (( b a s ) 0)  )))
  (lex.add.entry '("drawstring" nil ( ((d r oo s t ) 1) (( r i ng ) 2)  )))
  (lex.add.entry '("puss's" nil ( ((p u ) 1) (( s i z ) 0)  )))
  (lex.add.entry '("feast'd" nil ( ((f ii s t ) 1)  )))
  (lex.add.entry '("nesbit" nil ( ((n e z ) 1) (( b i t ) 0)  )))
  (lex.add.entry '("loyd" nil ( ((l oi d ) 1)  )))
  (lex.add.entry '("much's" nil ( ((m uh ) 1) (( ch i z ) 0)  )))
  (lex.add.entry '("first'm" nil ( ((f @@r s t m ) 1)  )))
  (lex.add.entry '("claybourne" nil ( ((k l ei ) 1) (( b oo n ) 0)  )))
  (lex.add.entry '("escalus" nil ( ((e s ) 1) (( k a ) 0) (( l @ s ) 0)  )))
  (lex.add.entry '("benvolio" nil ( ((b e n ) 0) (( v ou ) 1) (( l ii ) 0) (( ou ) 0)  )))
  (lex.add.entry '("mercutio" nil ( ((m @@r k ) 0) (( y uu ) 1) (( sh ii ) 0) (( ou ) 0)  )))
  (lex.add.entry '("capulet" nil ( ((k a p ) 1) (( y @ ) 0) (( l i t ) 0)  )))
  (lex.add.entry '("tybalt" nil ( ((t i ) 1) (( b @ lw t ) 0)  )))
  (lex.add.entry '("capulets" nil ( ((k a p ) 1) (( y @ ) 0) (( l @ t s ) 0)  )))
  (lex.add.entry '("capulet's" nil ( ((k a p ) 1) (( y @ ) 0) (( l @ t s ) 0)  )))
  (lex.add.entry '("mercutio's" nil ( ((m @@r k ) 0) (( y uu ) 1) (( sh ii ) 0) (( ou z ) 0)  )))
  (lex.add.entry '("mantua" nil ( ((m a n t ) 1) (( y uu ) 0) (( @ ) 0)  )))
  (lex.add.entry '("sticklewick" nil ( ((s t i k l! ) 1) (( w i k ) 2)  )))
  (lex.add.entry '("sticklewick's" nil ( ((s t i k l! ) 1) (( w i k s ) 2)  )))
  (lex.add.entry '("frogspawn" nil ( ((f r o g s ) 1) (( p oo n ) 2)  )))
  (lex.add.entry '("lucian" nil ( ((l uu ) 1) (( s ii ) 0) (( @ n ) 0)  )))
  (lex.add.entry '("samosata" nil ( ((s a ) 1) (( m @ ) 0) (( s a ) 1) (( t @ ) 0)  )))
  (lex.add.entry '("shinpads" nil ( ((sh i n ) 1) (( p a d z ) 2)  )))
  (lex.add.entry '("fifa" nil ( ((f ii ) 1) (( f @ ) 0)  )))
  (lex.add.entry '("scilly" nil ( ((s i ) 1) (( l ii ) 0)  )))
  (lex.add.entry '("scrummages" nil ( ((s k r uh ) 1) (( m i ) 0) (( jh i z ) 0)  )))
  (lex.add.entry '("lik" nil ( ((l i k ) 0)  )))
  (lex.add.entry '("pasuckuakohowog" nil ( ((p @ ) 0) (( s uh ) 1) (( k uh ) 0) (( w @ ) 0) (( k @ ) 0) (( h ow ) 1) (( w o g ) 0)  )))
  (lex.add.entry '("soc" nil ( ((s o k ) 1)  )))
  (lex.add.entry '("rimet" nil ( ((r i ) 1) (( m e ) 0)  )))
  (lex.add.entry '("dickins" nil ( ((d i ) 1) (( k i n z ) 0)  )))
  (lex.add.entry '("gingerbred" nil ( ((jh i n ) 1) (( jh @ ) 0) (( b r e d ) 1)  )))
  (lex.add.entry '("issun" nil ( ((i ) 1) (( sh @ n ) 0)  )))
  (lex.add.entry '("boshi" nil ( ((b o ) 1) (( sh ii ) 0)  )))
  (lex.add.entry '("issy" nil ( ((i ) 1) (( s ii ) 0)  )))
  (lex.add.entry '("ping's" nil ( ((p i ng z ) 1)  )))
  (lex.add.entry '("issy's" nil ( ((i ) 1) (( s ii z ) 0)  )))
  (lex.add.entry '("hight" nil ( ((h ai t ) 1)  )))
  (lex.add.entry '("bottletop" nil ( ((b o t l! ) 1) (( t o p ) 2)  )))
  (lex.add.entry '("i." nil ( ((ai ) 1)  )))
  (lex.add.entry '("mousehole" nil ( ((m ow s ) 1) (( h ou lw ) 2)  )))
  (lex.add.entry '("lesly" nil ( ((l e z ) 1) (( l ii ) 0)  )))
  (lex.add.entry '("didgeridoo" nil ( ((d i ) 1) (( jh @ ) 0) (( r i ) 0) (( d uu ) 1)  )))
  (lex.add.entry '("chinny" nil ( ((ch i ) 1) (( n ii ) 0)  )))
  (lex.add.entry '("farmboy" nil ( ((f aa m ) 1) (( b oi ) 2)  )))
  (lex.add.entry '("grahame" nil ( ((g r ei ) 1) (( @ m ) 0)  )))
  (lex.add.entry '("splish" nil ( ((s p l i sh ) 0)  )))
  (lex.add.entry '("moly" nil ( ((m ou ) 1) (( l ii ) 0)  )))
  (lex.add.entry '("bargewoman" nil ( ((b aa jh ) 1) (( w u ) 2) (( m @ n ) 0)  )))
  (lex.add.entry '("ma'am" nil ( ((m a ) 1) (( @ m ) 0)  )))
  (lex.add.entry '("washing's" nil ( ((w o ) 1) (( sh i ng z ) 0)  )))
  (lex.add.entry '("wooders" nil ( ((w u ) 1) (( d @ z ) 0)  )))
  (lex.add.entry '("cookham" nil ( ((k u ) 1) (( k @ m ) 0)  )))
  (lex.add.entry '("dene" nil ( ((d ii n ) 0)  )))



(lex.add.entry '("koshchey" nil ( ((k o sh ) 1) (( ch ii) 0)  )))
(lex.add.entry '("hansel's" nil ( ((h a n s l! z) 1)  )))
(lex.add.entry '("hansel" nil ( ((h a n s l!) 1)  )))
(lex.add.entry '("polymerase" nil ( ((p o ) 0) (( l i ) 1) (( m @ ) 0) (( r ei z) 0)  )))
(lex.add.entry '("cesario" nil ( ((s i ) 0) (( z eir ) 1) (( r ii ) 0) (( ou) 0)  )))
(lex.add.entry '("mccafferty" nil ( ((m @ ) 0) (( k a ) 1) (( f @ ) 0) (( t ii) 0)  )))
(lex.add.entry '("twoo" nil ( ((t @ ) 0) ((w uu) 1)  )))
(lex.add.entry '("allahabad" nil ( ((@ ) 0) (( l a ) 1) (( h @ ) 0) (( b a d) 0)  )))
(lex.add.entry '("maxie" nil ( ((m a k ) 1) (( s ii) 0)  )))
(lex.add.entry '("gretel" nil ( ((g r e ) 1) (( t @ lw) 0)  )))
(lex.add.entry '("hospitallers" nil ( ((h o ) 0) (( s p i ) 1) (( t a ) 0) (( l @ z) 0)  )))
(lex.add.entry '("footsoldiers" nil ( ((f u t ) 1) (( s ou lw ) 1) (( jh @ z) 0)  )))
(lex.add.entry '("chainmail" nil ( ((ch ei n ) 2) (( m ei lw) 1)  )))
(lex.add.entry '("vassily" nil ( ((v a ) 0) (( s i ) 1) (( l ii) 0)  )))
(lex.add.entry '("daynes" nil ( ((d ei n z) 1)  )))
(lex.add.entry '("usborne" nil ( ((uh z ) 1) (( b oo n) 0)  )))
(lex.add.entry '("climbdown" nil ( ((k l ai m ) 1) (( d ow n) 2)  )))
(lex.add.entry '("dunion" nil ( ((d uh n ) 1) (( y @ n) 0)  )))
(lex.add.entry '("dalmat" nil ( ((d aa lw ) 1) (( m @ t) 0)  )))
(lex.add.entry '("krak" nil ( ((k r aa k) 1)  )))
(lex.add.entry '("chillon" nil ( ((sh ii ) 0) (( y o n) 1)  )))
(lex.add.entry '("ord" nil ( ((oo d) 1)  )))
(lex.add.entry '("santander" nil ( ((s a n ) 2) (( t a n ) 2) (( d eir r) 1)  )))
(lex.add.entry '("sighthill" nil ( ((s ai t ) 1) (( h i lw) 2)  )))
(lex.add.entry '("onlg" nil ( ((ou n) 1) ((l ii) 0)  )))
(lex.add.entry '("aguecheek" nil ( ((ei ) 1) (( g y u ) 0) (( ch ii k) 2)  )))
(lex.add.entry '("asbury" nil ( ((a z ) 1) (( b @ ) 0) (( r ii) 0)  )))
(lex.add.entry '("mairi" nil ( ((m ai ) 1) (( r ii) 0)  )))
(lex.add.entry '("orsino's" nil ( ((oo ) 0) (( s ii ) 1) (( n ou z) 0)  )))
(lex.add.entry '("gartered" nil ( ((g aa ) 1) (( t @ d) 0)  )))
(lex.add.entry '("stowell" nil ( ((s t ou ) 1) (( @ lw) 0)  )))
(lex.add.entry '("christa" nil ( ((k r i s ) 1) (( t @) 0)  )))
(lex.add.entry '("passepartout" nil ( ((p a s ) 1) (( p aa ) 0) (( t uu ) 1)  )))
(lex.add.entry '("feste" nil ( ((f e s t) 1)  )))
(lex.add.entry '("passepartout's" nil ( ((p a s ) 1) (( p aa ) 0) (( t uu z ) 1)  )))
(lex.add.entry '("illyria" nil ( ((i ) 0) (( l i ) 1) (( r ii ) 0) (( @) 0)  )))
(lex.add.entry '("motte" nil ( ((m o t) 1)  )))
(lex.add.entry '("roehampton" nil ( ((r ou ) 1) (( h a m ) 0) (( t @ n) 0)  )))
(lex.add.entry '("phileas" nil ( ((f ii ) 1) (( l ii ) 0) (( @ s) 0)  )))
(lex.add.entry '("aouda's" nil ( ((aa ) 0) (( uu ) 1) (( d @ z) 0)  )))
(lex.add.entry '("quicklinks" nil ( ((k w i k ) 1) (( l i ng k s) 2)  )))
(lex.add.entry '("chevaliers" nil ( ((sh e ) 0) (( v a ) 1) (( l y e z) 0)  )))
(lex.add.entry '("malbork" nil ( ((m a lw ) 1) (( b oo k) 0)  )))
(lex.add.entry '("gretel's" nil ( ((g r e ) 1) (( t @ lw z) 0)  )))
(lex.add.entry '("dickins" nil ( ((d i ) 1) (( k i n z) 0)  )))
(lex.add.entry '("unzner" nil ( ((uh n z ) 1) (( n @ r) 0)  )))
(lex.add.entry '("alida" nil ( ((@ ) 0) (( l ii ) 1) (( d @) 0)  )))
(lex.add.entry '("greter" nil ( ((g r ii ) 1) (( t @ r) 0)  )))
(lex.add.entry '("firemaster" nil ( ((f ai ) 1) (( @ ) 0) (( m aa s ) 2) (( t @ r) 0)  )))
(lex.add.entry '("thwump" nil ( ((th w uh m p) 1)  )))
(lex.add.entry '("orsino" nil ( ((oo ) 0) (( s ii ) 1) (( n ou) 0)  )))
(lex.add.entry '("cid" nil ( ((s i d) 1)  )))
(lex.add.entry '("stott" nil ( ((s t o t) 1)  )))
(lex.add.entry '("hamas" nil ( ((h a ) 2) (( m a s) 1)  )))
(lex.add.entry '("afron" nil ( ((a f ) 1) (( r o n) 0)  )))
(lex.add.entry '("afron's" nil ( ((a f ) 1) (( r o n z) 0)  )))
(lex.add.entry '("boucicaut" nil ( ((b ou ) 1) (( s i ) 0) (( k oo t) 0)  )))
(lex.add.entry '("miz" nil ( ((m i z) 1)  )))
(lex.add.entry '("com" nil ( ((k o m) 1)  )))
(lex.add.entry '("koshchey's" nil ( ((k o sh ) 1) (( ch ii z) 0)  )))
(lex.add.entry '("dalmat's" nil ( ((d aa lw ) 1) (( m @ t s) 0)  )))
(lex.add.entry '("wakey" nil ( ((w ei ) 1) (( k ii) 0)  )))
(lex.add.entry '("brer" nil ( ((b r eir r) 1)  )))
(lex.add.entry '("massari" nil ( ((m a ) 0) (( s aa ) 1) (( r ii) 0)  )))
(lex.add.entry '("stower" nil ( ((s t ou ) 1) (( @ r) 0)  )))
(lex.add.entry '("muszynski" nil ( ((m u ) 0) (( s i n ) 1) (( s k ii) 0)  )))
(lex.add.entry '("aouda" nil ( ((aa ) 0) (( uu ) 1) (( d @) 0)  )))
(lex.add.entry '("aaaargh" nil ((( aa r g) 1)  )))
(lex.add.entry '("landslips" nil ( ((l a n d  ) 1) (( s l i p s) 2)  )))
(lex.add.entry '("batasuna" nil ( ((b a ) 2) (( t @ ) 0) (( s uu ) 1) (( n @) 0)  )))
(lex.add.entry '("weatherstaff" nil ( ((w e ) 1) (( dh @ ) 0) (( s t aa f) 2)  )))
(lex.add.entry '("blackheart" nil ( ((b l a k ) 1) (( h aa t) 2)  )))
(lex.add.entry '("ooof" nil ( ((oo ) 0) (( u f) 2)  )))
(lex.add.entry '("ts" nil ( ((t s) 1)  )))
(lex.add.entry '("strathclyde's" nil ( ((s t r @ th k ) 2) (( k l ai d z) 1)  )))
(lex.add.entry '("oldsmobile" nil ( ((ou lw d z ) 1) (( m ou ) 0) (( b ii lw) 2)  )))
(lex.add.entry '("c.c.t.v" nil (  ((s ii ) 2)   ((s ii ) 2)   ((t ii ) 2)   ((v ii ) 1)  )))
(lex.add.entry '("levassor" nil ( ((l e ) 0) (( v a ) 1) (( s @ r) 0)  )))
(lex.add.entry '("ovarian" nil ( ((ou ) 0) (( v eir ) 1) (( r ii ) 0) (( @ n) 0)  )))
(lex.add.entry '("seadog" nil ( ((s ii ) 1) (( d o g) 2)  )))
(lex.add.entry '("raceabout" nil ( ((r ei ) 1) (( s @ ) 0) (( b ow t) 2)  )))
(lex.add.entry '("houten" nil ( ((h ow ) 1) (( t @ n) 0)  )))
(lex.add.entry '("cardwell" nil ( ((k aa d ) 1) (( w e lw) 0)  )))
(lex.add.entry '("misselthwaite" nil ( ((m i s lw ) 1) (( th w ai t) 2)  )))
(lex.add.entry '("s.s.c" nil ( ((e s) 2) ((e s) 2) ((s ii) 1)  )))
(lex.add.entry '("studebaker" nil ( ((s t y uu d ) 1) (( b ei ) 2) (( k @ r) 0)  )))
(lex.add.entry '("ndenda" nil ( ((n d e n ) 1) (( d @) 0)  )))
(lex.add.entry '("haa" nil ( ((h aa) 1)  )))
(lex.add.entry '("har" nil ( ((h aa ) 1)  )))
(lex.add.entry '("fora" nil ( ((f o ) 1) (( r @) 0)  )))
(lex.add.entry '("pinchly's" nil ( ((p i n ch ) 1) (( l ii z) 2)  )))
(lex.add.entry '("cugnot" nil ( ((k uu ) 1) (( n y ou) 2)  )))
(lex.add.entry '("hissss" nil ( ((h i s) 1)  )))
(lex.add.entry '("medlock" nil ( ((m e d ) 1) (( l o k) 2)  )))
(lex.add.entry '("daynes" nil ( ((d ei n z) 1)  )))
(lex.add.entry '("lenoir" nil ( ((l @ ) 0) (( n w aa) 1)  )))
(lex.add.entry '("fishies" nil ( ((f i sh ) 1) (( ii z) 0)  )))
(lex.add.entry '("gho" nil ( ((g ou) 1)  )))
(lex.add.entry '("redbeard's" nil ( ((r e d ) 1) (( b eir d z) 2)  )))
(lex.add.entry '("rollo" nil ( ((r ou ) 1) (( l ou) 0)  )))
(lex.add.entry '("rodolphe" nil ( ((r ou ) 0) (( d o lw f) 1)  )))
(lex.add.entry '("rene" nil ( ((r e ) 2) (( n ei) 2)  )))
(lex.add.entry '("gottlieb" nil ( ((g o t ) 1) (( l ii b) 2)  )))
(lex.add.entry '("topolino" nil ( ((t o ) 1) (( p @ ) 0) (( l ii ) 1) (( n ou) 0)  )))
(lex.add.entry '("trevithick" nil ( ((t r e ) 0) (( v i ) 1) (( th i k) 0)  )))
(lex.add.entry '("hoddy" nil ( ((h o ) 1) (( d ii) 0)  )))
(lex.add.entry '("jenners" nil ( ((jh e ) 1) (( n @ z) 0)  )))
(lex.add.entry '("crawlies" nil ( ((k r oo ) 1) (( l ii z) 0)  )))
(lex.add.entry '("asbury" nil ( ((a z ) 1) (( b @ ) 0) (( r ii) 0)  )))
(lex.add.entry '("mugdock" nil ( ((m uh g ) 1) (( d o k) 2)  )))
(lex.add.entry '("dickon's" nil ( ((d i ) 1) (( k @ n z) 0)  )))
(lex.add.entry '("byeeee" nil ( ((b ai ) 1) (( ii) 2)  )))
(lex.add.entry '("murrie" nil ( ((m uh ) 1) (( r ii) 0)  )))
(lex.add.entry '("flodden" nil ( ((f l o ) 1) (( d @ n) 0)  )))
(lex.add.entry '("iglesias" nil ( ((i ) 0) (( g l e ) 1) (( s ii ) 0) (( @ s) 0)  )))
(lex.add.entry '("guarde" nil ( ((g aa d) 2)  )))
(lex.add.entry '("berta" nil ( ((b @@r ) 1) (( t @) 0)  )))
(lex.add.entry '("arfons" nil ( ((aa ) 1) (( v o n z) 0)  )))
(lex.add.entry '("soham" nil ( ((s ou ) 1) (( h a m) 0)  )))
(lex.add.entry '("panhard" nil ( ((p a n ) 0) (( h aa d) 1)  )))
(lex.add.entry '("etienne" nil ( ((e ) 2) (( t ii ) 0) (( e n ) 1)  )))
(lex.add.entry '("harr" nil ( ((h aa ) 1)  )))
(lex.add.entry '("blackheart's" nil ( ((b l a k ) 2) (( h aa t s) 1)  )))
(lex.add.entry '("barmy" nil ( ((b aa ) 1) (( m ii) 0)  )))
(lex.add.entry '("rusell" nil ( ((r uh ) 1) (( s @ lw) 0)  )))
(lex.add.entry '("bullnose" nil ( ((b u lw ) 1) (( n ou z) 2)  )))
(lex.add.entry '("cardonald" nil ( ((k aa ) 1) (( d @ ) 0) (( n @ lw d) 2)  )))
(lex.add.entry '("wooah" nil ( ((w ou ) 1)   )))
(lex.add.entry '("pinchly" nil ( ((p i n ch ) 1) (( l ii ) 2)  )))
(lex.add.entry '("topolinos" nil ( ((t o ) 1) (( p @ ) 0) (( l ii ) 1) (( n ou z) 0)  )))
(lex.add.entry '("dempster" nil ( ((d e m ) 1) (( s t @ ) 0)  )))
(lex.add.entry '("dickon" nil ( ((d i ) 1) (( k @ n) 0)  )))
(lex.add.entry '("chocol" nil ( ((ch o ) 1) (( k o lw) 0)  )))
(lex.add.entry '("knyff" nil ( ((k n ii f) 1)  )))
(lex.add.entry '("neuhaus" nil ( ((n oi ) 1) (( h ow s) 2)  )))
(lex.add.entry '("quetzalcoatl" nil ( ((k e t ) 2) (( s @ lw ) 0) (( k ou ) 0) (( a t l!) 1)  )))
(lex.add.entry '("kingom" nil (((k i ng) 1) ((d @ m) 0)) ))
(lex.add.entry '("waterstone's" nil ( ((w oo ) 1) (( t @ ) 0) (( s t ou n z) 2)  )))
(lex.add.entry '("stott" nil ( ((s t o t) 1)  )))
(lex.add.entry '("gloopy" nil ( ((g l uu ) 1) (( p ii) 0)  )))
(lex.add.entry '("montefiore" nil ( ((m o n ) 2) (( t e ) 0) (( f ii ) 0) (( oo ) 1)  (( r ei) 0)  )))
(lex.add.entry '("benz" nil ( ((b e n z) 1)  )))
(lex.add.entry '("enrique" nil ( ((e n ) 0) (( r ii ) 1) (( k ei) 0)  )))
(lex.add.entry '("milngavie" nil ( ((m i lw n ) 1) (( g aa ) 1) (( v ii) 0)  )))
(lex.add.entry '("daimler's" nil ( ((d ei m ) 1) (( l @ z) 0)  )))
(lex.add.entry '("montezuma" nil ( ((m o n ) 1) (( t @ ) 0) (( z uu ) 1) (( m @) 0)  )))
(lex.add.entry '("yorrick" nil ( ((y oo ) 1) (( r i k) 0)  )))
(lex.add.entry '("hernan" nil ( ((h @@r ) 1) (( n @ n) 0)  )))
(lex.add.entry '("lindt" nil ( ((l i n t) 1)  )))
(lex.add.entry '("miz" nil ( ((m i z) 1)  )))
(lex.add.entry '("laertes" nil ( ((l e ) 2) (( @@r) 1)  (( t ii z) 0)  )))
(lex.add.entry '("sebag" nil ( ((s ii ) 1) (( b a g) 2)  )))
(lex.add.entry '("coenraad" nil ( ((k ou n ) 1)  (( r aa d ) 2)  )))
(lex.add.entry '("mcleish's" nil ( ((m @ ) 0) (( k l ii ) 1) (( sh i s) 0)  )))
(lex.add.entry '("goldsworthy" nil ( ((g ou lw d z ) 1) (( w @@r ) 2) (( dh ii) 0)  )))
(lex.add.entry '("grrrrgh" nil ( ((g r @@r) 1)  )))
(lex.add.entry '("zzzzz" nil ( ((z ) 1)  )))
(lex.add.entry '("kensit" nil ( ((k e n ) 1) (( z i t) 0)  )))
(lex.add.entry '("rampton" nil ( ((r a m ) 1) (( t @ n) 0)  )))
(lex.add.entry '("woooaaah" nil ( ((w uu ) 1) )))
(lex.add.entry '("baaaa" nil ( ((b aa ) 1)  )))
(lex.add.entry '("stowell" nil ( ((s t ou ) 1) (( @ lw) 0)  )))
(lex.add.entry '("spike's" nil ( ((s p ai k s) 1)  )))
)

(set! unilex-rpx-backoff_rules
'(
(l! l)
(n! n)
(iii ii)
(eir e)
(@@r @r)
(n @)
(aa @)
(ae @)
(i @)
(irr @)
(iii @)
(ei @)
(er @)
(a @)
(eir @)
(uw @)
(@@r @)
(e @)
(oo @)
(our @)
(ow @)
(o @)
(oi @)
(uh @)
(u @)
(urr @)
(uuu @)
(i@ @)
(ur @)
(hw w )
(s z)
(_ #)

))

(lex.create "unilex-rpx")
(lex.set.compile.file (path-append unilexdir "unilex-rpx.out"))
(lex.set.phoneset "unilex")
(lex.set.lts.method 'unilex-rpx_lts_function)
;(lex.set.pos.map english_pos_map_wp39_to_wp20)
(lex.set.pos.map nil)
(unilex-rpx_addenda)

(provide 'unilex-rpx)
